<?php 
	$APP_NAME = "CS Tri-Mentoring";
	$MATCH_TITLE_NAME = "Name";
	$MAX_PRIORITY = 16;
	$MIN_PRIORITY = 1;
	
	$MATCH_NOT_USED = 0;
	$MATCH_EXACT = 1;
	$MATCH_INEXACT = 2;
	$MATCH_STRONG_EXACT_WITH_PROVIDED = 3;
	$MATCH_SIMILAR_TEXT = 4;
	$MATCH_WITHIN_RANGE = 5;
	$MATCH_WEAK_EXACT_WITH_PROVIDED = 6;
?>